#!/bin/bash
valor=$(df -h | grep /net | tail -1 |  awk '{ print $5 }' | cut -d% -f1)
if [ ! -z "$valor" ];then
	if [ $valor -gt 90 ]; then
		$((ps -aux | grep zenity | grep Conky > /dev/null ) || (zenity --info --title="Conky informa" --text="/net esta casi lleno, vacia datos del disco."> /dev/null 2>&1) &) ;
	fi;
fi
